"""finish owner model

Revision ID: 91c1d0c1a2af
Revises: afa024c36be3
Create Date: 2024-05-27 12:40:09.376738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c1d0c1a2af'
down_revision = 'afa024c36be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
